approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  element-source@0.0.5:
    peerDependencies:
      "@types/react": ">=18.0.0"
      react: ">=17.0.1"
